/// Files: drivers/net/can/usb/usb_8dev.c
/// Fix: 3d3925ff6433f98992685a9679613a2cc97f3ce2
/// Fixes: 0024d8ad1639e32d717445c69ca813fd19c2a91c

virtual detect

@err exists@
position p;
@@

usb_8dev_start_xmit(...)
{
...
failed:
	can_free_echo_skb(...);
		...
nomembuf:
	usb_free_urb(...);

nomem:
*		dev_kfree_skb(...);@p
...
}

@script:python depends on detect@
p << err.p;
@@

coccilib.report.print_report(p[0], 'ERROR: CVE-2022-28388')
